// ============================================================================
// Generated by `supabase gen types typescript` (via Supabase MCP) from the live
// schema of project vtarcekyiuqfebbfxurq. Regenerate after any migration.
// ============================================================================

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      activities: {
        Row: {
          calories: number;
          created_at: string;
          day_number: number;
          duration_min: number;
          id: string;
          intensity: string | null;
          notes: string | null;
          nutrition: string | null;
          photo_url: string | null;
          source: string;
          type: string;
          user_id: string;
          water_liters: number;
        };
        Insert: {
          calories?: number;
          created_at?: string;
          day_number: number;
          duration_min?: number;
          id?: string;
          intensity?: string | null;
          notes?: string | null;
          nutrition?: string | null;
          photo_url?: string | null;
          source?: string;
          type: string;
          user_id: string;
          water_liters?: number;
        };
        Update: {
          calories?: number;
          created_at?: string;
          day_number?: number;
          duration_min?: number;
          id?: string;
          intensity?: string | null;
          notes?: string | null;
          nutrition?: string | null;
          photo_url?: string | null;
          source?: string;
          type?: string;
          user_id?: string;
          water_liters?: number;
        };
        Relationships: [];
      };
      badges: {
        Row: { code: string; created_at: string; id: string; tier: number; user_id: string };
        Insert: { code: string; created_at?: string; id?: string; tier?: number; user_id: string };
        Update: {
          code?: string;
          created_at?: string;
          id?: string;
          tier?: number;
          user_id?: string;
        };
        Relationships: [];
      };
      challenge_days: {
        Row: {
          day_number: number;
          id: string;
          state: string;
          updated_at: string;
          user_id: string;
        };
        Insert: {
          day_number: number;
          id?: string;
          state?: string;
          updated_at?: string;
          user_id: string;
        };
        Update: {
          day_number?: number;
          id?: string;
          state?: string;
          updated_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      comment_likes: {
        Row: { comment_id: string; user_id: string };
        Insert: { comment_id: string; user_id: string };
        Update: { comment_id?: string; user_id?: string };
        Relationships: [];
      };
      comments: {
        Row: {
          activity_id: string;
          body: string;
          created_at: string;
          id: string;
          user_id: string;
        };
        Insert: {
          activity_id: string;
          body: string;
          created_at?: string;
          id?: string;
          user_id: string;
        };
        Update: {
          activity_id?: string;
          body?: string;
          created_at?: string;
          id?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      duels: {
        Row: { created_at: string; id: string; rival_id: string; user_id: string };
        Insert: { created_at?: string; id?: string; rival_id: string; user_id: string };
        Update: { created_at?: string; id?: string; rival_id?: string; user_id?: string };
        Relationships: [];
      };
      integrations: {
        Row: {
          access_token: string | null;
          expires_at: string | null;
          provider: string;
          refresh_token: string | null;
          user_id: string;
        };
        Insert: {
          access_token?: string | null;
          expires_at?: string | null;
          provider: string;
          refresh_token?: string | null;
          user_id: string;
        };
        Update: {
          access_token?: string | null;
          expires_at?: string | null;
          provider?: string;
          refresh_token?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      kudos: {
        Row: {
          activity_id: string;
          created_at: string;
          id: string;
          reaction: string | null;
          user_id: string;
        };
        Insert: {
          activity_id: string;
          created_at?: string;
          id?: string;
          reaction?: string | null;
          user_id: string;
        };
        Update: {
          activity_id?: string;
          created_at?: string;
          id?: string;
          reaction?: string | null;
          user_id?: string;
        };
        Relationships: [];
      };
      mentions: {
        Row: { comment_id: string; id: string; mentioned_user_id: string; read: boolean };
        Insert: { comment_id: string; id?: string; mentioned_user_id: string; read?: boolean };
        Update: { comment_id?: string; id?: string; mentioned_user_id?: string; read?: boolean };
        Relationships: [];
      };
      notifications: {
        Row: {
          actor_id: string | null;
          body: string;
          created_at: string;
          id: string;
          kind: string;
          read: boolean;
          user_id: string;
        };
        Insert: {
          actor_id?: string | null;
          body: string;
          created_at?: string;
          id?: string;
          kind: string;
          read?: boolean;
          user_id: string;
        };
        Update: {
          actor_id?: string | null;
          body?: string;
          created_at?: string;
          id?: string;
          kind?: string;
          read?: boolean;
          user_id?: string;
        };
        Relationships: [];
      };
      profiles: {
        Row: {
          avatar_url: string | null;
          created_at: string;
          id: string;
          level: number;
          name: string;
          streak_freezes: number;
          theme: string;
          xp: number;
        };
        Insert: {
          avatar_url?: string | null;
          created_at?: string;
          id: string;
          level?: number;
          name?: string;
          streak_freezes?: number;
          theme?: string;
          xp?: number;
        };
        Update: {
          avatar_url?: string | null;
          created_at?: string;
          id?: string;
          level?: number;
          name?: string;
          streak_freezes?: number;
          theme?: string;
          xp?: number;
        };
        Relationships: [];
      };
      xp_events: {
        Row: { amount: number; created_at: string; id: string; reason: string; user_id: string };
        Insert: { amount: number; created_at?: string; id?: string; reason: string; user_id: string };
        Update: {
          amount?: number;
          created_at?: string;
          id?: string;
          reason?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: { [_ in never]: never };
    Functions: { [_ in never]: never };
    Enums: { [_ in never]: never };
    CompositeTypes: { [_ in never]: never };
  };
};
